<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="model" nsURI="http:///model.ecore" nsPrefix="model">
  <eClassifiers xsi:type="ecore:EClass" name="RoomType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="price" ordered="false"
        lowerBound="1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//Integer"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxNrOfGuests" ordered="false"
        lowerBound="1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//Integer"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" ordered="false"
        lowerBound="1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="roomTypeEnum" ordered="false"
        lowerBound="1" eType="#//RoomTypeEnum"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="RoomTypeEnum">
    <eLiterals name="Singlebed"/>
    <eLiterals name="Doublebed" value="1"/>
    <eLiterals name="Luxurysuite" value="2">
      <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
        <details key="originalName" value="Luxury suite"/>
      </eAnnotations>
    </eLiterals>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Experience" eSuperTypes="#//AbstractExtra">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nrOfSpots" ordered="false"
        lowerBound="1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//Integer"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="experienceStatusEnum" ordered="false"
        lowerBound="1" eType="#//ExperienceStatusEnum"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractExtra" eSuperTypes="#//Extra">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ID" ordered="false" lowerBound="1"
        eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="price" ordered="false"
        lowerBound="1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//Integer"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" lowerBound="1"
        eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" ordered="false"
        lowerBound="1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Extra" abstract="true" interface="true">
    <eOperations name="getPrice" ordered="false" lowerBound="1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//Integer"/>
    <eOperations name="getID" ordered="false" lowerBound="1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    <eOperations name="getName" ordered="false" lowerBound="1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    <eOperations name="getDescription" ordered="false" lowerBound="1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    <eOperations name="isAvailable" ordered="false" lowerBound="1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//Boolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ExperienceStatusEnum">
    <eLiterals name="ready"/>
    <eLiterals name="maintenance" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Product" eSuperTypes="#//AbstractExtra">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stock" ordered="false"
        lowerBound="1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//Integer"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="productStatusEnum" ordered="false"
        lowerBound="1" eType="#//ProductStatusEnum"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ProductStatusEnum">
    <eLiterals name="inStock"/>
    <eLiterals name="outOfStock" value="1"/>
    <eLiterals name="restocking" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Room">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numberID" ordered="false"
        lowerBound="1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//Integer"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="roomStatusEnum" ordered="false"
        lowerBound="1" eType="#//RoomStatusEnum"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="roomType" ordered="false"
        lowerBound="1" eType="#//RoomType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="RoomStatusEnum">
    <eLiterals name="Vacant"/>
    <eLiterals name="Busy" value="1"/>
    <eLiterals name="Maintenance" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExtraHandler">
    <eOperations name="exists" ordered="false" lowerBound="1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//Boolean">
      <eParameters name="ID" ordered="false" lowerBound="1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//Integer"/>
    </eOperations>
    <eOperations name="addExtra" ordered="false" lowerBound="1">
      <eParameters name="price" ordered="false" lowerBound="1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//Integer"/>
      <eParameters name="ID" ordered="false" lowerBound="1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//String"/>
      <eParameters name="name" ordered="false" lowerBound="1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//String"/>
      <eParameters name="description" ordered="false" lowerBound="1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    </eOperations>
    <eOperations name="removeExtra" ordered="false" lowerBound="1">
      <eParameters name="extra" ordered="false" lowerBound="1" eType="#//Extra"/>
    </eOperations>
    <eOperations name="getExtra" ordered="false" lowerBound="1" eType="#//Extra">
      <eParameters name="ID" ordered="false" lowerBound="1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//Integer"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="extraTable" ordered="false"
        upperBound="-1" eType="#//IntegerToExtraMap"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="extra" ordered="false"
        upperBound="-1" eType="#//Extra"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="intToExtraMap" ordered="false"
        upperBound="-1" eType="#//IntegerToExtraMap" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntegerToExtraMap">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" ordered="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" ordered="false"
        lowerBound="1" eType="#//Extra"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RoomHandler">
    <eOperations name="exists" ordered="false" lowerBound="1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//Boolean">
      <eParameters name="ID" ordered="false" lowerBound="1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//Integer"/>
    </eOperations>
    <eOperations name="addRoom" ordered="false" lowerBound="1">
      <eParameters name="numberID" ordered="false" lowerBound="1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//Integer"/>
      <eParameters name="roomType" ordered="false" lowerBound="1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    </eOperations>
    <eOperations name="removeRoom" ordered="false" lowerBound="1">
      <eParameters name="room" ordered="false" lowerBound="1" eType="#//Room"/>
    </eOperations>
    <eOperations name="getRoom" ordered="false" lowerBound="1" eType="#//Room">
      <eParameters name="ID" ordered="false" lowerBound="1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//Integer"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="roomTable" ordered="false"
        upperBound="-1" eType="#//IntegerToRoomMap"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="room" ordered="false" upperBound="-1"
        eType="#//Room"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="integerToRoomMap" ordered="false"
        upperBound="-1" eType="#//IntegerToRoomMap" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntegerToRoomMap">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" ordered="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" ordered="false"
        lowerBound="1" eType="#//Room"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Calendar">
    <eOperations name="getCap" ordered="false" upperBound="-1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//Integer">
      <eParameters name="start" ordered="false" lowerBound="1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//Integer"/>
      <eParameters name="end" ordered="false" lowerBound="1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//Integer"/>
      <eParameters name="roomType" ordered="false" lowerBound="1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    </eOperations>
    <eOperations name="setCap" ordered="false" lowerBound="1">
      <eParameters name="start" ordered="false" lowerBound="1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//Integer"/>
      <eParameters name="end" ordered="false" lowerBound="1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//Integer"/>
      <eParameters name="roomType" ordered="false" lowerBound="1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//String"/>
      <eParameters name="nrOfRooms" ordered="false" lowerBound="1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//Integer"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="roomTypeCapTable" ordered="false"
        upperBound="-1" eType="#//RoomTypes"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stringToListsMap" ordered="false"
        lowerBound="1" eType="#//StringToListsMap" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RoomTypes">
    <eOperations name="exists" ordered="false" lowerBound="1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//Boolean">
      <eParameters name="ID" ordered="false" lowerBound="1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//Integer"/>
    </eOperations>
    <eOperations name="addRoomType" ordered="false" lowerBound="1">
      <eParameters name="roomType" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="price" ordered="false" lowerBound="1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//Integer"/>
      <eParameters name="maxNrOfGuests" ordered="false" lowerBound="1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//Integer"/>
      <eParameters name="description" ordered="false" lowerBound="1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    </eOperations>
    <eOperations name="removeRoomType" ordered="false" lowerBound="1">
      <eParameters name="roomType" ordered="false" lowerBound="1" eType="#//RoomType"/>
    </eOperations>
    <eOperations name="getRoomType" ordered="false" lowerBound="1" eType="#//RoomType">
      <eParameters name="name" ordered="false" lowerBound="1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="roomTypeTable" ordered="false"
        upperBound="-1" eType="#//StringToRoomType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="roomType" ordered="false"
        upperBound="-1" eType="#//RoomType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stringToRoomType" ordered="false"
        upperBound="-1" eType="#//StringToRoomType" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StringToRoomType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" ordered="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" ordered="false"
        lowerBound="1" eType="#//StringToRoomType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StringToListsMap">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" ordered="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" ordered="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IMaintenanceProvidesForBooking" abstract="true"
      interface="true">
    <eOperations name="canBook" ordered="false" lowerBound="1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//Boolean">
      <eParameters name="roomType" ordered="false" lowerBound="1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//String"/>
      <eParameters name="start" ordered="false" lowerBound="1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//String"/>
      <eParameters name="end" ordered="false" lowerBound="1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    </eOperations>
    <eOperations name="makeBooking" ordered="false" lowerBound="1">
      <eParameters name="roomType" ordered="false" lowerBound="1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//String"/>
      <eParameters name="start" ordered="false" lowerBound="1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//String"/>
      <eParameters name="end" ordered="false" lowerBound="1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    </eOperations>
    <eOperations name="removeBooking" ordered="false" lowerBound="1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//Integer">
      <eParameters name="roomType" ordered="false" lowerBound="1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//String"/>
      <eParameters name="nrOfRooms" ordered="false" lowerBound="1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//Integer"/>
      <eParameters name="start" ordered="false" lowerBound="1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//String"/>
      <eParameters name="end" ordered="false" lowerBound="1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    </eOperations>
    <eOperations name="setBookingAsActive" ordered="false" lowerBound="1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//Integer">
      <eParameters name="bookingRef" ordered="false" lowerBound="1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IRoomMaintenance" abstract="true" interface="true">
    <eOperations name="addRoom" ordered="false" lowerBound="1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//Integer">
      <eParameters name="numberID" ordered="false" lowerBound="1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//Integer"/>
      <eParameters name="roomType" ordered="false" lowerBound="1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    </eOperations>
    <eOperations name="removeRoom" ordered="false" lowerBound="1">
      <eParameters name="room" ordered="false" lowerBound="1" eType="#//Room"/>
    </eOperations>
    <eOperations name="addRoomType" ordered="false" lowerBound="1">
      <eParameters name="roomType" ordered="false" lowerBound="1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//String"/>
      <eParameters name="price" ordered="false" lowerBound="1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//Integer"/>
      <eParameters name="maxNrOfGuests" ordered="false" lowerBound="1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//Integer"/>
      <eParameters name="description" ordered="false" lowerBound="1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    </eOperations>
    <eOperations name="removeRoomType" ordered="false" lowerBound="1">
      <eParameters name="roomType" ordered="false" lowerBound="1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    </eOperations>
    <eOperations name="getRooms" ordered="false" lowerBound="1"/>
    <eOperations name="getRoomTypes" ordered="false" lowerBound="1"/>
    <eOperations name="getRoom" ordered="false" lowerBound="1" eType="#//Room">
      <eParameters name="ID" ordered="false" lowerBound="1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//Integer"/>
    </eOperations>
    <eOperations name="getRoomType" ordered="false" lowerBound="1" eType="#//RoomType">
      <eParameters name="ID" ordered="false" lowerBound="1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//Integer"/>
    </eOperations>
    <eOperations name="editRoomStatus" ordered="false" lowerBound="1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//Integer">
      <eParameters name="roomID" ordered="false" lowerBound="1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//Integer"/>
      <eParameters name="status" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EEnumerator"/>
    </eOperations>
    <eOperations name="getRoomStatus" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EEnumerator">
      <eParameters name="roomID" ordered="false" lowerBound="1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//Integer"/>
    </eOperations>
    <eOperations name="editRoomType" ordered="false" lowerBound="1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//Integer">
      <eParameters name="roomType" ordered="false" lowerBound="1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//String"/>
      <eParameters name="price" ordered="false" lowerBound="1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//Integer"/>
      <eParameters name="maxNrOfGuests" ordered="false" lowerBound="1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//Integer"/>
      <eParameters name="description" ordered="false" lowerBound="1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    </eOperations>
    <eOperations name="editRoom" ordered="false" lowerBound="1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//Integer">
      <eParameters name="numberID" ordered="false" lowerBound="1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//Integer"/>
      <eParameters name="roomType" ordered="false" lowerBound="1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IExtrasMaintenance" abstract="true"
      interface="true">
    <eOperations name="addExtra" ordered="false" lowerBound="1">
      <eParameters name="price" ordered="false" lowerBound="1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//Integer"/>
      <eParameters name="ID" ordered="false" lowerBound="1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//String"/>
      <eParameters name="name" ordered="false" lowerBound="1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//String"/>
      <eParameters name="description" ordered="false" lowerBound="1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    </eOperations>
    <eOperations name="removeExtra" ordered="false" lowerBound="1">
      <eParameters name="extra" ordered="false" lowerBound="1" eType="#//Extra"/>
    </eOperations>
    <eOperations name="getExtras" ordered="false" lowerBound="1"/>
    <eOperations name="getExtra" ordered="false" lowerBound="1">
      <eParameters name="ID" ordered="false" lowerBound="1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//Integer"/>
    </eOperations>
    <eOperations name="editExtra" ordered="false" lowerBound="1">
      <eParameters name="price" ordered="false" lowerBound="1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//Integer"/>
      <eParameters name="ID" ordered="false" lowerBound="1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//String"/>
      <eParameters name="name" ordered="false" lowerBound="1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//String"/>
      <eParameters name="description" ordered="false" lowerBound="1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExtrasMaintenance">
    <eStructuralFeatures xsi:type="ecore:EReference" name="extras" ordered="false"
        lowerBound="1" eType="#//ExtraHandler" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RoomMaintenance">
    <eStructuralFeatures xsi:type="ecore:EReference" name="roomTypes" ordered="false"
        lowerBound="1" eType="#//RoomTypes"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rooms" ordered="false"
        lowerBound="1" eType="#//RoomHandler" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MaintenanceProvidesForBooking">
    <eOperations name="canBook" ordered="false" lowerBound="1">
      <eParameters name="roomType" ordered="false" lowerBound="1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//String"/>
      <eParameters name="nrOfRooms" ordered="false" lowerBound="1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//Integer"/>
      <eParameters name="start" ordered="false" lowerBound="1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//String"/>
      <eParameters name="end" ordered="false" lowerBound="1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    </eOperations>
    <eOperations name="makeBooking" ordered="false" lowerBound="1">
      <eParameters name="roomType" ordered="false" lowerBound="1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//String"/>
      <eParameters name="nrOfRooms" ordered="false" lowerBound="1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//Integer"/>
      <eParameters name="start" ordered="false" lowerBound="1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//String"/>
      <eParameters name="end" ordered="false" lowerBound="1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    </eOperations>
    <eOperations name="removeBooking" ordered="false" lowerBound="1">
      <eParameters name="roomType" ordered="false" lowerBound="1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//String"/>
      <eParameters name="nrOfRooms" ordered="false" lowerBound="1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//Integer"/>
      <eParameters name="start" ordered="false" lowerBound="1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//String"/>
      <eParameters name="end" ordered="false" lowerBound="1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    </eOperations>
    <eOperations name="setBookingAsActive" ordered="false" lowerBound="1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//Integer">
      <eParameters name="bookingRef" ordered="false" lowerBound="1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="calendar" ordered="false"
        lowerBound="1" eType="#//Calendar"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="roomTypes" ordered="false"
        lowerBound="1" eType="#//RoomTypes" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rooms" ordered="false"
        lowerBound="1" eType="#//RoomHandler" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
